// controllers/dayController.ts
import { Prisma } from '@prisma/client';
import { Response } from 'express';
import { AuthRequest, DayInput, DayResponse } from '../types';
import { AppError } from '../middleware/errorHandler';
import { prisma } from '../lib/prisma';

/** Default sort for activities on a day (matches Prisma schema: time → position → createdAt). */
const activityListOrderBy = [
  { time: 'asc' },
  { position: 'asc' },
  { createdAt: 'asc' },
] as Prisma.ActivityOrderByWithRelationInput[];

const activityNotDeletedWhere = { deletedAt: null } as Prisma.ActivityWhereInput;

// Helper function to format day response
const formatDayResponse = (day: any): DayResponse => {
  return {
    id: day.id,
    vacationId: day.vacationId,
    homestayId: day.homestayId,
    date: day.date.toISOString().split('T')[0], // YYYY-MM-DD
    notes: day.notes,
    createdAt: day.createdAt.toISOString(),
    updatedAt: day.updatedAt.toISOString(),
  };
};

// ============================================================================
// HELPER: AUTO-GENERATE DAYS FOR A VACATION
// ============================================================================

/**
 * Auto-generates Day records for a vacation from startDate to endDate.
 * Skips days that already exist.
 * Called when creating or updating a vacation.
 */
export const autoGenerateDays = async (
  vacationId: string,
  startDate: Date,
  endDate: Date
): Promise<void> => {
  const currentDate = new Date(startDate);
  
  while (currentDate <= endDate) {
    // Check if day already exists for this date
    const existingDay = await prisma.day.findUnique({
      where: {
        vacationId_date: {
          vacationId,
          date: new Date(currentDate),
        },
      },
    });

    // Create day if it doesn't exist
    if (!existingDay) {
      await prisma.day.create({
        data: {
          vacationId,
          date: new Date(currentDate),
        },
      });
    }

    // Move to next day
    currentDate.setDate(currentDate.getDate() + 1);
  }
};

// ============================================================================
// GET ALL DAYS FOR A VACATION
// ============================================================================

export const getDays = async (req: AuthRequest, res: Response) => {
  try {
    const vacationId = Array.isArray(req.params.vacationId) ? req.params.vacationId[0] : req.params.vacationId;

    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    // Verify vacation exists and user owns it
    const vacation = await prisma.vacation.findUnique({
      where: { id: vacationId },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Get all days for this vacation, sorted by date
    const days = await prisma.day.findMany({
      where: { vacationId },
      orderBy: { date: 'asc' },
      include: {
        homestay: true,
        activities: {
          where: activityNotDeletedWhere, // Exclude hard-deleted activities
          orderBy: activityListOrderBy,
        },
      },
    });

    res.json(days.map(formatDayResponse));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to retrieve days', { error });
  }
};

// ============================================================================
// GET SINGLE DAY
// ============================================================================

export const getDay = async (req: AuthRequest, res: Response) => {
  try {
    const vacationId = Array.isArray(req.params.vacationId) ? req.params.vacationId[0] : req.params.vacationId;
    const dayId = Array.isArray(req.params.dayId) ? req.params.dayId[0] : req.params.dayId;

    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    // Verify vacation exists and user owns it
    const vacation = await prisma.vacation.findUnique({
      where: { id: vacationId },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Get day with activities
    const day = await prisma.day.findUnique({
      where: { id: dayId },
      include: {
        homestay: true,
        activities: {
          where: activityNotDeletedWhere, // Exclude hard-deleted activities
          orderBy: activityListOrderBy,
        },
      },
    });

    if (!day) {
      throw new AppError(404, 'Day not found');
    }

    // Verify day belongs to this vacation
    if (day.vacationId !== vacationId) {
      throw new AppError(404, 'Day not found in this vacation');
    }

    res.json(formatDayResponse(day));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to retrieve day', { error });
  }
};

// ============================================================================
// CREATE DAY (Manual creation - rare, days are auto-generated)
// ============================================================================

export const createDay = async (req: AuthRequest, res: Response) => {
  try {
    const vacationId = Array.isArray(req.params.vacationId) ? req.params.vacationId[0] : req.params.vacationId;
    const { date: dateStr, homestayId, notes } = req.body as DayInput;

    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    if (!dateStr) {
      throw new AppError(400, 'Date is required');
    }

    // Verify vacation exists and user owns it
    const vacation = await prisma.vacation.findUnique({
      where: { id: vacationId },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Parse date
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) {
      throw new AppError(400, 'Invalid date format');
    }

    // Verify date is within vacation range
    if (date < vacation.startDate || date > vacation.endDate) {
      throw new AppError(400, 'Date must be within vacation date range');
    }

    const duplicate = await prisma.day.findUnique({
      where: {
        vacationId_date: {
          vacationId,
          date,
        },
      },
    });
    if (duplicate) {
      throw new AppError(409, 'A day already exists for this date');
    }

    // If homestayId provided, verify it belongs to this vacation
    if (homestayId) {
      const homestay = await prisma.homestay.findUnique({
        where: { id: homestayId },
      });

      if (!homestay || homestay.vacationId !== vacationId) {
        throw new AppError(404, 'Homestay not found in this vacation');
      }
    }

    // Create day
    const day = await prisma.day.create({
      data: {
        vacationId,
        date,
        homestayId: homestayId || null,
        notes: notes || null,
      },
      include: {
        homestay: true,
        activities: {
          where: activityNotDeletedWhere,
          orderBy: activityListOrderBy,
        },
      },
    });

    res.status(201).json(formatDayResponse(day));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to create day', { error });
  }
};

// ============================================================================
// UPDATE DAY
// ============================================================================

export const updateDay = async (req: AuthRequest, res: Response) => {
  try {
    const vacationId = Array.isArray(req.params.vacationId) ? req.params.vacationId[0] : req.params.vacationId;
    const dayId = Array.isArray(req.params.dayId) ? req.params.dayId[0] : req.params.dayId;
    const { date: dateStr, homestayId, notes } = req.body;

    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    // Verify vacation exists and user owns it
    const vacation = await prisma.vacation.findUnique({
      where: { id: vacationId },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Get day
    const day = await prisma.day.findUnique({
      where: { id: dayId },
    });

    if (!day || day.vacationId !== vacationId) {
      throw new AppError(404, 'Day not found');
    }

    // If updating date, verify it's within vacation range
    if (dateStr) {
      const newDate = new Date(dateStr);
      if (isNaN(newDate.getTime())) {
        throw new AppError(400, 'Invalid date format');
      }

      if (newDate < vacation.startDate || newDate > vacation.endDate) {
        throw new AppError(400, 'Date must be within vacation date range');
      }

      const clash = await prisma.day.findFirst({
        where: {
          vacationId,
          date: newDate,
          NOT: { id: dayId },
        },
      });
      if (clash) {
        throw new AppError(409, 'A day already exists for this date');
      }
    }

    // If updating homestayId, verify it belongs to this vacation
    if (homestayId !== undefined && homestayId !== null) {
      const homestay = await prisma.homestay.findUnique({
        where: { id: homestayId },
      });

      if (!homestay || homestay.vacationId !== vacationId) {
        throw new AppError(404, 'Homestay not found in this vacation');
      }
    }

    // Update day
    const updatedDay = await prisma.day.update({
      where: { id: dayId },
      data: {
        ...(dateStr && { date: new Date(dateStr) }),
        ...(homestayId !== undefined && { homestayId }),
        ...(notes !== undefined && { notes }),
      },
      include: {
        homestay: true,
        activities: {
          where: activityNotDeletedWhere,
          orderBy: activityListOrderBy,
        },
      },
    });

    res.json(formatDayResponse(updatedDay));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to update day', { error });
  }
};

// ============================================================================
// DELETE DAY (Moves all activities to unassigned pool)
// ============================================================================

export const deleteDay = async (req: AuthRequest, res: Response) => {
  try {
    const vacationId = Array.isArray(req.params.vacationId) ? req.params.vacationId[0] : req.params.vacationId;
    const dayId = Array.isArray(req.params.dayId) ? req.params.dayId[0] : req.params.dayId;

    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    // Verify vacation exists and user owns it
    const vacation = await prisma.vacation.findUnique({
      where: { id: vacationId },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Get day
    const day = await prisma.day.findUnique({
      where: { id: dayId },
    });

    if (!day || day.vacationId !== vacationId) {
      throw new AppError(404, 'Day not found');
    }

    // Move all activities to unassigned pool (dayId → null)
    await prisma.activity.updateMany({
      where: { dayId },
      data: { dayId: null } as unknown as Prisma.ActivityUncheckedUpdateManyInput,
    });

    // Delete day
    await prisma.day.delete({
      where: { id: dayId },
    });

    res.json({ success: true, message: 'Day deleted. Activities moved to unassigned pool.' });
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to delete day', { error });
  }
};