import { Response } from 'express';
import { AuthRequest, VacationInput, VacationResponse } from '../types';
import { AppError } from '../middleware/errorHandler';
import { prisma } from '../lib/prisma';
import { autoGenerateDays } from './dayController';

// Helper function to format vacation response
const formatVacationResponse = (vacation: any): VacationResponse => {
  const days = vacation.days?.map((day: any) => ({
    id: day.id,
    vacationId: day.vacationId,
    date: day.date.toISOString().split('T')[0],
    homestayId: day.homestayId,
    notes: day.notes,
    activities: day.activities?.map((activity: any) => ({
      id: activity.id,
      dayId: activity.dayId,
      vacationId: activity.vacationId,
      type: activity.type,
      name: activity.name,
      location: activity.location,
      coordinates: activity.coordinates,
      googlePlacesId: activity.googlePlacesId,
      time: activity.time,
      duration: activity.duration,
      timeConstraint: activity.timeConstraint,
      priority: activity.priority,
      source: activity.source,
      notes: activity.notes,
      estimatedCost: activity.estimatedCost,
      metadata: activity.metadata,
      createdAt: activity.createdAt.toISOString(),
      updatedAt: activity.updatedAt.toISOString(),
    })) || [],
    createdAt: day.createdAt.toISOString(),
    updatedAt: day.updatedAt.toISOString(),
  })) || [];

  return {
    id: vacation.id,
    userId: vacation.userId,
    name: vacation.name,
    startDate: vacation.startDate.toISOString().split('T')[0],
    endDate: vacation.endDate.toISOString().split('T')[0],
    version: vacation.version,
    parentVacationId: vacation.parentVacationId,
    variant: vacation.variant,
    homestays: vacation.homestays || [],
    days,
    createdAt: vacation.createdAt.toISOString(),
    updatedAt: vacation.updatedAt.toISOString(),
  };
};

// ============================================================================
// CREATE VACATION
// ============================================================================

export const createVacation = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const { name, startDate, endDate } = req.body as VacationInput;

    // Validation
    if (!name || !startDate || !endDate) {
      throw new AppError(400, 'Name, startDate, and endDate are required');
    }

    const start = new Date(startDate);
    const end = new Date(endDate);

    if (start >= end) {
      throw new AppError(400, 'Start date must be before end date');
    }

    // Create vacation
    const vacation = await prisma.vacation.create({
      data: {
        userId: req.user.id,
        name,
        startDate: start,
        endDate: end,
        version: 1,
      },
    });

    await autoGenerateDays(vacation.id, start, end);

    const vacationWithDays = await prisma.vacation.findUnique({
      where: { id: vacation.id },
      include: {
        homestays: true,
        days: {
          orderBy: { date: 'asc' },
          include: {
            activities: true,
          },
        },
      },
    });

    if (!vacationWithDays) {
      throw new AppError(500, 'Failed to load vacation after create');
    }

    res.status(201).json(formatVacationResponse(vacationWithDays));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to create vacation', { error });
  }
};

// ============================================================================
// GET ALL VACATIONS FOR USER
// ============================================================================

export const getVacations = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const vacations = await prisma.vacation.findMany({
      where: {
        userId: req.user.id,
        parentVacationId: null, // Only get originals, not variants
      },
      include: {
        homestays: true,
        days: {
          include: {
            activities: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    const formatted = vacations.map(formatVacationResponse);
    res.json(formatted);
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to fetch vacations', { error });
  }
};

// ============================================================================
// GET SINGLE VACATION
// ============================================================================

export const getVacation = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;

    const vacation = await prisma.vacation.findUnique({
      where: { id },
      include: {
        homestays: true,
        days: {
          include: {
            activities: true,
          },
          orderBy: {
            date: 'asc',
          },
        },
      },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    res.json(formatVacationResponse(vacation));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to fetch vacation', { error });
  }
};

// ============================================================================
// UPDATE VACATION
// ============================================================================

export const updateVacation = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
    const { name, startDate, endDate } = req.body as Partial<VacationInput>;

    // Check ownership
    const vacation = await prisma.vacation.findUnique({
      where: { id },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    const nextStart = startDate ? new Date(startDate) : vacation.startDate;
    const nextEnd = endDate ? new Date(endDate) : vacation.endDate;

    // Validate dates if either is being changed
    if (startDate || endDate) {
      if (nextStart >= nextEnd) {
        throw new AppError(400, 'Start date must be before end date');
      }
    }

    // Update vacation
    const updated = await prisma.vacation.update({
      where: { id },
      data: {
        ...(name && { name }),
        ...(startDate && { startDate: nextStart }),
        ...(endDate && { endDate: nextEnd }),
      },
    });

    if (startDate || endDate) {
      await autoGenerateDays(id, nextStart, nextEnd);
    }

    const updatedWithDays = await prisma.vacation.findUnique({
      where: { id },
      include: {
        homestays: true,
        days: {
          orderBy: { date: 'asc' },
          include: {
            activities: true,
          },
        },
      },
    });

    if (!updatedWithDays) {
      throw new AppError(500, 'Failed to load vacation after update');
    }

    res.json(formatVacationResponse(updatedWithDays));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to update vacation', { error });
  }
};

// ============================================================================
// DELETE VACATION
// ============================================================================

export const deleteVacation = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;

    // Check ownership
    const vacation = await prisma.vacation.findUnique({
      where: { id },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Delete vacation (cascades to days, activities, homestays)
    await prisma.vacation.delete({
      where: { id },
    });

    res.json({ success: true, message: 'Vacation deleted' });
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to delete vacation', { error });
  }
};

// ============================================================================
// CREATE VACATION VARIANT
// ============================================================================

export const createVacationVariant = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
    const { variant } = req.body as { variant: string };

    if (!variant) {
      throw new AppError(400, 'Variant name is required');
    }

    // Check ownership
    const parentVacation = await prisma.vacation.findUnique({
      where: { id },
      include: {
        homestays: true,
        days: {
          include: {
            activities: true,
          },
        },
      },
    });

    if (!parentVacation) {
      throw new AppError(404, 'Parent vacation not found');
    }

    if (parentVacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    // Create variant vacation (clone of parent)
    const variantVacation = await prisma.vacation.create({
      data: {
        userId: req.user.id,
        name: `${parentVacation.name} - ${variant}`,
        startDate: parentVacation.startDate,
        endDate: parentVacation.endDate,
        parentVacationId: id,
        variant,
        version: 1,
      },
      include: {
        homestays: true,
        days: {
          include: {
            activities: true,
          },
        },
      },
    });

    res.status(201).json(formatVacationResponse(variantVacation));
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to create vacation variant', { error });
  }
};

// ============================================================================
// GET VACATION VERSIONS
// ============================================================================

export const getVacationVersions = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      throw new AppError(401, 'Unauthorized');
    }

    const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;

    // Check ownership
    const vacation = await prisma.vacation.findUnique({
      where: { id },
    });

    if (!vacation) {
      throw new AppError(404, 'Vacation not found');
    }

    if (vacation.userId !== req.user.id) {
      throw new AppError(403, 'You do not have access to this vacation');
    }

    const versions = await prisma.vacationVersion.findMany({
      where: { vacationId: id },
      orderBy: { versionNumber: 'desc' },
    });

    const formatted = versions.map((v) => ({
      versionNumber: v.versionNumber,
      createdAt: v.createdAt.toISOString(),
      reason: v.reason,
      snapshot: v.snapshot,
    }));

    res.json(formatted);
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }
    throw new AppError(500, 'Failed to fetch versions', { error });
  }
};